COLOR_FONDO = "#FFF7F0"
COLOR_PRINCIPAL = "#B99AD9"
COLOR_SECUNDARIO = "#EFA0B6"
COLOR_TEXTO = "#55466B"

INTEGRANTES = "Javier, Luciana y Micaela"
UNIVERSIDAD = "UNPILAR"
CARRERA = "Desarrollo de Software"
